adm/urls.py
from django.contrib.auth import views as auth_views

from . import views
from rechum.urls import *


urlpatterns = [
    path('home/', views.home, name='home'),
    path('administracion/', include([
        path('unidades-organizacionales/', include([
            path('', views.UnidadOrgListView.as_view(), name='unidadorg_list'),
            path('agregar/', views.UnidadOrgCreateView.as_view(), name='unidadorg_create'),
            path('<int:pk>/actualizar/', views.UnidadOrgUpdateView.as_view(), name='unidadorg_update'),
            path('<int:pk>/', views.UnidadOrgDetailView.as_view(), name='unidadorg_detail'),
            path('<int:pk>/trabajadores/', views.trab_unidad, name='trab-unidad'),
            path('<int:pk>/eliminar/', views.UnidadOrgDeleteView.as_view(), name='unidadorg_delete')
        ])),
        path('secciones-sindicales/', include([
            path('', views.SecSinListView.as_view(), name='seccionsindical_list'),
            path('agregar/', views.SecSinCreateView.as_view(), name='seccionsindical_create'),
            path('<int:pk>/actualizar/', views.SecSinUpdateView.as_view(), name='seccionsindical_update'),
            path('<int:pk>/', views.SecSinDetailView.as_view(), name='seccionsindical_detail'),
            path('<int:pk>/eliminar/', views.SecSinDeleteView.as_view(), name='seccionsindical_delete')
        ])),
        path('departamentos/', include([
            path('', views.DepListView.as_view(), name='departamento_list'),
            path('unidad/<int:unidad_id>/', views.DepListView.as_view(), name='departamento_unidad_list'),
            path('agregar/', views.DepCreateView.as_view(), name='departamento_create'),
            path('<int:pk>/actualizar/', views.DepUpdateView.as_view(), name='departamento_update'),
            path('<int:pk>/', views.DepDetailView.as_view(), name='departamento_detail'),
            path('<int:pk>/eliminar/', views.DepDeleteView.as_view(), name='departamento_delete')
        ])),
        path('escalas-salariales/', include([
            path('', views.EscSalListView.as_view(), name='escalasalarial_list'),
            path('agregar/', views.EscSalCreateView.as_view(), name='escalasalarial_create'),
            path('<int:pk>/actualizar/', views.EscSalUpdateView.as_view(), name='escalasalarial_update'),
            path('<int:pk>/', views.EscSalDetailView.as_view(), name='escalasalarial_detail'),
            path('<int:pk>/eliminar/', views.EscSalDeleteView.as_view(), name='escalasalarial_delete')
        ])),
        path('cargos/', include([
            path('', views.CargoListView.as_view(), name='cargo_list'),
            path('agregar/', views.CargoCreateView.as_view(), name='cargo_create'),
            path('<int:pk>/actualizar/', views.CargoUpdateView.as_view(), name='cargo_update'),
            path('<int:pk>/', views.CargoDetailView.as_view(), name='cargo_detail'),
            path('<int:pk>/eliminar/', views.CargoDeleteView.as_view(), name='cargo_delete')
        ])),
        path('calificaciones/', include([
            path('', views.CalListView.as_view(), name='calificacion_list'),
            path('agregar/', views.CalCreateView.as_view(), name='calificacion_create'),
            path('<int:pk>/actualizar/', views.CalUpdateView.as_view(), name='calificacion_update'),
            path('<int:pk>/', views.CalDetailView.as_view(), name='calificacion_detail'),
            path('<int:pk>/eliminar/', views.CalDeleteView.as_view(), name='calificacion_delete')
        ])),
        path('especialidades/', include([
            path('', views.EspListView.as_view(), name='especialidad_list'),
            path('agregar/', views.EspCreateView.as_view(), name='especialidad_create'),
            path('<int:pk>/actualizar/', views.EspUpdateView.as_view(), name='especialidad_update'),
            path('<int:pk>/', views.EspDetailView.as_view(), name='especialidad_detail'),
            path('<int:pk>/eliminar/', views.EspDeleteView.as_view(), name='especialidad_delete')
        ])),
    ])),
    path('logout/', login_required(auth_views.logout), name='logout'),
    path('unidad_organizacional/', login_required(views.gestionar_unidad_org), name='gestionarUnidadOrg'),
    path('calificacion/', login_required(views.gestionar_calificacion), name='gestionarCalificacion'),
    path('departamento/', login_required(views.gestionar_departamento), name='gestionarDepartamento'),
    path('cargo/', login_required(views.gestionar_cargo), name='gestionarCargo'),
    path('especialidad/', login_required(views.gestionar_especialidad), name='gestionarEspecialidad'),
    path('seccion_sindical/', login_required(views.gestionar_seccion_sindical), name='gestionarSeccionSindical'),
    path('adicionar_unidad_organizacional/', login_required(views.adicionar_uo), name='adicionarUO'),
    path('editar_unidad_organizacional/<int:pk>/', login_required(views.editar_uo), name='editarUO'),
    path('detalle_unidad_organizacional/<int:pk>/', login_required(views.DetalleUo.as_view()), name='detalleUO'),
    path('eliminar_unidad_organizacional/<int:pk>/', login_required(views.eliminar_uo), name='eliminarUO'),
    path('adicionar_seccion_sindical/', login_required(views.adicionar_ss), name='adicionarSS'),
    path('editar_seccion_sindical/<int:pk>/', login_required(views.editar_ss), name='editarSS'),
    path('detalle_seccion_sindical/<int:pk>/', login_required(views.DetalleSs.as_view()), name='detalleSS'),
    path('eliminar_seccion_sindical/<int:pk>/', login_required(views.eliminar_ss), name='eliminarSS'),
    path('adicionar_departamento/', login_required(views.adicionar_departamento), name='adicionarDepartamento'),
    path('editar_departamento/<int:pk>/', login_required(views.editar_departamento), name='editarDepartamento'),
    path('detalle_departamento/<int:pk>/', login_required(views.DetalleDepartamento.as_view()),
         name='detalleDepartamento'),
    path('eliminar_departamento/<int:pk>/', login_required(views.eliminar_departamento), name='eliminarDepartamento'),
    path('adicionar_cargo/', login_required(views.adicionar_cargo), name='adicionarCargo'),
    path('editar_cargo/<int:pk>/', login_required(views.editar_cargo), name='editarCargo'),
    path('detalle_cargo/<int:pk>/', login_required(views.DetalleCargo.as_view()), name='detalleCargo'),
    path('eliminar_cargo/<int:pk>/', login_required(views.eliminar_cargo), name='eliminarCargo'),
    path('adicionar_calificacion/', login_required(views.adicionar_calificacion), name='adicionarCalificacion'),
    path('editar_calificacion/<int:pk>/', login_required(views.editar_calificacion), name='editarCalificacion'),
    path('detalle_calificacion/<int:pk>/', login_required(views.DetalleCalificacion.as_view()),
         name='detalleCalificacion'),
    path('eliminar_calificacion/<int:pk>/', login_required(views.eliminar_calificacion),
         name='eliminarCalificacion'),
    path('adicionar_especialidad/', login_required(views.adicionar_especialidad), name='adicionarEspecialidad'),
    path('editar_especialidad/<int:pk>/', login_required(views.editar_especialidad), name='editarEspecialidad'),
    path('detalle_especialidad/<int:pk>/', login_required(views.DetalleEspecialidad.as_view()),
         name='detalleEspecialidad'),
    path('eliminar_especialidad/<int:pk>/', login_required(views.eliminar_especialidad), name='eliminarEspecialidad'),
]

ausentismo/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('ausentismo/', login_required(views.gestionar_ausentismo), name='gestionarAusentismo'),
    path('listar_ausentismo/<int:pk>/', login_required(views.listar_ausentismo), name='listarAusentismo'),
    path('adicionar_ausentismo/', login_required(views.adicionar_ausentismo), name='adicionarAusentismo'),
    path('editar_ausentismo/<int:idtrab>/<int:pk>/', login_required(views.editar_ausentismo), name='editarAusentismo'),
    path('eliminar_ausentismo/<int:idtrab>/<int:pk>/', login_required(views.eliminar_ausentismo),
         name='eliminarAusentismo'),

    path('vista_reporte_ausentismo/', login_required(views.reporte), name='visualizarReporteAusentismo'),
    path('exportar_ausentismo/', login_required(views.exportar), name='exportarReporteAusentismo'),

    path('registro_tarjeta_SNC/', login_required(views.gestionar_tarjeta_snc), name='gestionarRegistroTarjetaSNC'),
    path('listar_registro_tarjetaSNC/<int:pk>/', login_required(views.listar_tarjeta_snc),
         name='listarRegistroTarjetaSNC'),
    path('adicionar_registro_tarjetaSNC/', login_required(views.adicionar_tarjeta_snc),
         name='adicionarRegistroTarjetaSNC'),
    path('editar_registro_tarjetaSNC/<int:idtrab>/<int:pk>/', login_required(views.editar_tarjeta_snc),
         name='editarRegistroTarjetaSNC'),
    path('eliminar_registro_tarjetaSNC/<int:idtrab>/<int:pk>/', login_required(views.eliminar_tarjeta_snc),
         name='eliminarRegistroTarjetaSNC'),
]

rechum/urls.py
from decorator_include import decorator_include
from django.contrib import admin
from django.contrib.auth.views import login
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', decorator_include(login_required, 'principal.urls')),
    path('', login, name='login_up'),
    path('rh/', include([
        path('', decorator_include(login_required, 'adm.urls')),
        path('', decorator_include(login_required, 'ges_trab.urls')),
        path('', decorator_include(login_required, 'plantilla.urls')),
        path('', decorator_include(login_required, 'capacitacion.urls')),
        path('parte-tiempo/', decorator_include(login_required, 'parte_tiempo.urls')),
        path('subsidios/', decorator_include(login_required, 'subsidio.urls')),
        path('datos-prenomina/', decorator_include(login_required, 'datos_prenom.urls')),
        path('ausentismo/', decorator_include(login_required, 'ausentismo.urls')),
        path('capacitacion/', decorator_include(login_required, 'capacitacion.urls')),
    ])),
    path('entrada-datos/', decorator_include(login_required, 'entrada_datos.urls')),
    path('facturacion/', decorator_include(login_required, 'facturacion.urls')),
    path('pr3/', decorator_include(login_required, 'pr3.urls')),
    path('pren/', decorator_include(login_required, 'prenomina15.urls')),
    re_path('^select2/', include('django_select2.urls'))
    # path('__debug__/', include(debug_toolbar.urls))
]

ausentismo/models.py
import datetime

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from dateutil.relativedelta import relativedelta

from adm.models import UnidadOrg, Departamento
from ges_trab.models import Trabajador


class TipoIncidencia:
    VACACIONES = 'V'
    CERTIFICADO_MEDICO = 'Cm'
    LICENCIA_SIN_SUELDO = 'LSS'
    MISION_INTERNACIONALISTA = 'MI'
    INTERRUPCION = 'I'
    BAJA = 'B'
    ALTA = 'A',
    MOVILIZACION = 'M'
    ENFERMO = 'E'
    RECESO_LABORAL_RETRIBUIDO = 'Fr'
    PRESTACION_SOCIAL = 'F'

    choices = (
        (VACACIONES, 'Vacaciones'),
        (CERTIFICADO_MEDICO, 'Certificado Médico'),
        (LICENCIA_SIN_SUELDO, 'Licencia sin Sueldo'),
        (MISION_INTERNACIONALISTA, 'Misión Internacionalista'),
        (INTERRUPCION, 'Interrupción'),
        (BAJA, 'Baja'),
        (ALTA, 'Alta'),
        (MOVILIZACION, 'Movilización'),
        (ENFERMO, 'Enfermo'),
        (RECESO_LABORAL_RETRIBUIDO, 'Receso Laboral Retribuido'),
        (PRESTACION_SOCIAL, 'Prestación Social')
    )


class Ausencia(models.Model):
    codigo_trab = models.ForeignKey(Trabajador, on_delete=models.CASCADE, default='', verbose_name='trabajador')
    fecha = models.DateField(verbose_name='fecha de registro')
    horas = models.DecimalField(decimal_places=2, max_digits=3)
    causal = models.CharField(max_length=3, choices=TipoIncidencia.choices, default=TipoIncidencia.VACACIONES)

    @property
    def trabajador(self):
        return self.codigo_trab

    def __str__(self):
        return '{} => {} => {}'.format(self.codigo_trab, self.fecha, self.causal)


class Mes:
    ENERO = 'Enero'
    FEBRERO = 'Febrero'
    MARZO = 'Marzo'
    ABRIL = 'Abril'
    MAYO = 'Mayo'
    JUNIO = 'Junio'
    JULIO = 'Julio'
    AGOSTO = 'Agosto'
    SEPTIEMBRE = 'Septiembre'
    OCTUBRE = 'Octubre'
    NOVIEMBRE = 'Noviembre'
    DICIEMBRE = 'Diciembre'

    choices = ((ENERO, 'Enero'), (FEBRERO, 'Febrero'), (MARZO, 'Marzo'), (ABRIL, 'Abril'), (MAYO, 'Mayo'),
               (JUNIO, 'Junio'), (JULIO, 'Julio'), (AGOSTO, 'Agosto'), (SEPTIEMBRE, 'Septiembre'), (OCTUBRE, 'Octubre'),
               (NOVIEMBRE, 'Noviembre'), (DICIEMBRE, 'Diciembre'))


class TarjetaCNC(models.Model):
    codigo_trab = models.ForeignKey(Trabajador, on_delete=models.CASCADE, default='', verbose_name='Trabajador')
    mes = models.CharField(choices=Mes.choices, default=datetime.datetime.now().strftime('%m'), validators=[
        MaxValueValidator(12), MinValueValidator(1)
    ], max_length=10)
    anno = models.PositiveSmallIntegerField(verbose_name='año', default=int(datetime.datetime.now().year), validators=[
        MaxValueValidator(2150), MinValueValidator(1900)
    ])
    cant_dias = models.PositiveIntegerField(verbose_name='cant. días')
    salario = models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Salario', default=0.00)

    @property
    def trabajador(self):
        return self.codigo_trab

    def __str__(self):
        return '{} => {} => {}'.format(self.codigo_trab, self.mes + '/' + str(self.anno),
                                       self.salario)

ausentismo/templates/Eliminar_Ausentismo.html
<div class="modal-dialog" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <div class="modal-content">
        <form role="form"
                {% if not error %}
              action="{% url 'eliminarAusentismo' idtrab object.pk %}" method="post">
                {% endif %}
        {% csrf_token %}
        <div class="modal-header">
            <h6><strong>Eliminar Registro de Ausentismo</strong></h6>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if not error %}
                        <p style="text-align: justify">¿Estás seguro que deseas eliminar la ausencia asociado al trabajador
                            <strong>"{{ object.codigo_trab.primer_nombre }}
                                {{ object.codigo_trab.segundo_nombre }} {{ object.codigo_trab.apellidos }}"</strong>?</p>
                    {% else %}
                        <h1 style="text-align: center; color: #dc3545"><i class="fa fa-warning"></i></h1>
                        <h6 style="text-align: center; color: #dc3545"><strong>{{ error }}</strong></h6>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <div class="col-lg-12 text-right">
                {% if not error %}
                    <input type="submit" class="btn btn-danger" name="submit" value="Eliminar">
                {% endif %}
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    Cancelar
                </button>
            </div>
        </div>
        </form>
    </div>
</div>

ausentismo/templates/Eliminar_TarjetaSNC.html
<div class="modal-dialog" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <div class="modal-content">
        <form role="form"
                {% if not error %}
              action="{% url 'eliminarRegistroTarjetaSNC' idtrab object.pk %}" method="post">
                {% endif %}
        {% csrf_token %}
        <div class="modal-header">
            <h5><strong>Eliminar entrada de Tarjeta SNC</strong></h5>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if not error %}
                        <p>¿Estás seguro que deseas eliminar la entrada asociada al trabajador
                            <strong>"{{ object.codigo_trab.primer_nombre }}
                                {{ object.codigo_trab.segundo_nombre }} {{ object.codigo_trab.apellidos }}"</strong>?</p>
                    {% else %}
                        <h1 style="text-align: center; color: #dc3545"><i class="fa fa-warning"></i></h1>
                        <h6 style="text-align: center; color: #dc3545"><strong>{{ error }}</strong></h6>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <div class="col-lg-12 text-right">
                {% if not error %}
                    <input type="submit" class="btn btn-danger" name="submit" value="Eliminar">
                {% endif %}
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    Cancelar
                </button>
            </div>
        </div>
        </form>
    </div>
</div>

ausentismo/templates/Gestionar_TarjetaSNC.html
{% extends "base.html" %}
{% load static %}
{% block title %}Gestionar Tarjeta SNC{% endblock %}
{% block styles %}
    <style type="text/css">
        .has-error {
            border-color: #dc3545;
            box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.25);
        }
        td, th {
            padding: 1px!important;
        }
    </style>
{% endblock %}
{% block migas %}
    <ol class="breadcrumb" style="margin-top: 56px; opacity: 0.9; position: fixed;
    top: 0; right: 0; left: 0; z-index: 1000;">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Inicio</a></li>
        <li class="breadcrumb-item active" aria-current="page">Gestionar Tarjeta SNC</li>
    </ol>
{% endblock %}
{% block content %}
    <div class=content align="center"><h5><strong>Gestionar Tarjeta SNC</strong></h5></div>
    <div class="container" role="main" style="font-size: smaller; width: 1000px">
        <br>
        <div class="row">
            <div class="col-lg-12">
                <table class="display" cellspacing="0" width="100%" id="tabla_sub">
                    <thead>
                    <tr>
                        <th>Unidad Organizacional</th>
                        <th>Departamento</th>
                        <th>Código / Trabajador</th>
                        <th>Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in list_trab %}
                        <tr>

                            <td>{{ i.unidad_org }}</td>
                            <td>{{ i.departamento }}</td>
                            <td>{{ i.codigo_interno }} {{ i.primer_nombre }} {{ i.segundo_nombre }} {{ i.apellidos }}</td>
                            <td width="60" nowrap>
                                <div class="icon-acciones" align="center">
                                    <a id="{{ i.pk }}- {{ i.primer_nombre }} {{ i.apellidos }}"
                                       class="badge badge-pill badge-primary addTarjetaSNC">
                                        <i class="fa fa-plus" title="Registrar entrada Tarjeta SNC"
                                           style="color: white;"></i>
                                    </a>
                                    <a href="{% url 'listarRegistroTarjetaSNC' i.pk %}"
                                       class="badge badge-pill badge-secondary">
                                        <i class="fa fa-list" title="Visualizar entradas Tarjeta SNC"
                                           style="color: white;"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <th>Unidad Organizacional</th>
                    <th>Departamento</th>
                    <th>Código / Trabajador</th>
                    <td style="padding: 6px 6px !important;"></td>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <div id="popup" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form id="formularioSub" role="form" action="{% url 'adicionarRegistroTarjetaSNC' %}" method="post">
                    <div class="modal-header">
                        <h6><strong>Adicionar entrada Tarjeta SNC</strong></h6>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body mio">
                        {% csrf_token %}
                        <div class="row">
                            <input id="user" name="codigo_trab" value="" type="hidden">
                            <div class="col-sm-3"><strong> Mes:</strong>{{ form.mes }}
                                <div style="color: red;">{{ form.mes.errors }}</div>
                            </div>
                            <div class="col-sm-3"><strong> A&ntilde;o:</strong>{{ form.anno }}
                                <div style="color: red;">{{ form.ann.errors }}</div>
                            </div>
                            <div class="col-sm-3"><strong> Cant. D&iacute;as:</strong>{{ form.cant_dias }}
                                <div style="color: red;">{{ form.cant_dias.errors }}</div>
                            </div>
                            <div class="col-sm-3"><strong> Salario:</strong>{{ form.salario }}
                                <div style="color: red;">{{ form.salario.errors }}</div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="col-lg-12 text-right">
                            <input id="enviar" type="submit" class="btn btn-primary" name="submit" value="Guardar">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">
                                Cancelar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script type="text/javascript">
        var exp1 = "^([0-9]{1,5}){1}(([,]{1})([0-9]{0,2}))?";
        var exp2 = "^[0-9]{1,2}$";
        var exp3 = "^[0-9]{4}$";

        function validarFormulario() {
            if (validarAnno() && validarDias() && validarSalario()) {
                $('#enviar').removeAttr('disabled');
            } else {
                $('#enviar').attr('disabled', '');
            }
        }

        $(document).ready(function () {
            validarFormulario();
        });

        function validarAnno() {
            if ($('#id_anno')[0].value.match(exp3)) {
                $('#id_anno').removeClass('has-error');
                return true;
            } else {
                $('#id_anno').addClass('has-error');
                return false;
            }
        }

        function validarSalario() {
            var sal=$('#id_salario')[0].value;
            if (sal.match(exp1) && sal.length <= 8){
                $('#id_salario').removeClass('has-error');
                return true;
            } else {
                $('#id_salario').addClass('has-error');
                return false;
            }
        }

        function validarDias() {
            var dias=$('#id_cant_dias')[0].value;
            if ($(dias.match(exp2)) && dias <=30) {
                $('#id_cant_dias').removeClass('has-error');
                return true;
            } else {
                $('#id_cant_dias').addClass('has-error');
                return false;
            }
        }

        $('#id_cant_dias, #id_anno, #id_salario').on('change', function () {
            validarFormulario();
        }).on('keyup', function () {
            validarFormulario();
        });


        $("#id_anno").prop("readonly", true).datepicker({
            format: "yyyy",
            viewMode: "years",
            minViewMode: "years"
        });

    </script>
    <script type="text/javascript">

        $('.badge.badge-pill.badge-primary.addTarjetaSNC').click(function () {
            var nombre = this.id.split('-');
            $('#popup input#user').prop('value', nombre[0]);
            $('#formularioSub .modal-header h5 strong').html('Registrar entrada Tarjeta SNC a'+nombre[1]);
            $('#popup').modal('show');
        });
        {% if form.errors or edit %}
            $('#popup').modal('show');
        {% endif %}


        $(document).ready(function () {
            // Setup - add a text input to each footer cell
            $('#tabla_sub tfoot th').each(function () {
                var title = $(this).text();
                $(this).html('<input class="form-control" style="font-size: smaller" type="text" placeholder="Buscar ' + title + '" />');
            });

            // DataTable
            var table = $('#tabla_sub').DataTable({
                "language": {
                    processing: "Procesando...",
                    search: "Buscar:",
                    lengthMenu: "Mostrar _MENU_ registros",
                    info: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    infoEmpty: "Mostrando un total de 0 registros",
                    infoFiltered: "(filtrado de un total de _MAX_ registros)",
                    infoPostFix: "",
                    loadingRecords: "Cargando...",
                    zeroRecords: "No se encontraron resultados",
                    emptyTable: "Ningún dato disponible en esta tabla",
                    paginate: {
                        first: "Último",
                        previous: "Anterior",
                        next: "Siguiente",
                        last: "Último"
                    }
                }
            });

            // Apply the search
            table.columns().every(function () {
                var that = this;

                $('input', this.footer()).on('keyup change', function () {
                    if (that.search() !== this.value) {
                        that.search(this.value).draw();
                    }
                });
            });
        });
    </script>
{% endblock %}

ausentismo/templates/Reporte_TarjetaSNC.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ausentismo/templates/Reporte_TarjetaSNC_Template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>