adm/urls.py
from django.contrib.auth import views as auth_views

from . import views
from rechum.urls import *


urlpatterns = [
    path('home/', views.home, name='home'),
    path('administracion/', include([
        path('unidades-organizacionales/', include([
            path('', views.UnidadOrgListView.as_view(), name='unidadorg_list'),
            path('agregar/', views.UnidadOrgCreateView.as_view(), name='unidadorg_create'),
            path('<int:pk>/actualizar/', views.UnidadOrgUpdateView.as_view(), name='unidadorg_update'),
            path('<int:pk>/', views.UnidadOrgDetailView.as_view(), name='unidadorg_detail'),
            path('<int:pk>/trabajadores/', views.trab_unidad, name='trab-unidad'),
            path('<int:pk>/eliminar/', views.UnidadOrgDeleteView.as_view(), name='unidadorg_delete')
        ])),
        path('secciones-sindicales/', include([
            path('', views.SecSinListView.as_view(), name='seccionsindical_list'),
            path('agregar/', views.SecSinCreateView.as_view(), name='seccionsindical_create'),
            path('<int:pk>/actualizar/', views.SecSinUpdateView.as_view(), name='seccionsindical_update'),
            path('<int:pk>/', views.SecSinDetailView.as_view(), name='seccionsindical_detail'),
            path('<int:pk>/eliminar/', views.SecSinDeleteView.as_view(), name='seccionsindical_delete')
        ])),
        path('departamentos/', include([
            path('', views.DepListView.as_view(), name='departamento_list'),
            path('unidad/<int:unidad_id>/', views.DepListView.as_view(), name='departamento_unidad_list'),
            path('agregar/', views.DepCreateView.as_view(), name='departamento_create'),
            path('<int:pk>/actualizar/', views.DepUpdateView.as_view(), name='departamento_update'),
            path('<int:pk>/', views.DepDetailView.as_view(), name='departamento_detail'),
            path('<int:pk>/eliminar/', views.DepDeleteView.as_view(), name='departamento_delete')
        ])),
        path('escalas-salariales/', include([
            path('', views.EscSalListView.as_view(), name='escalasalarial_list'),
            path('agregar/', views.EscSalCreateView.as_view(), name='escalasalarial_create'),
            path('<int:pk>/actualizar/', views.EscSalUpdateView.as_view(), name='escalasalarial_update'),
            path('<int:pk>/', views.EscSalDetailView.as_view(), name='escalasalarial_detail'),
            path('<int:pk>/eliminar/', views.EscSalDeleteView.as_view(), name='escalasalarial_delete')
        ])),
        path('cargos/', include([
            path('', views.CargoListView.as_view(), name='cargo_list'),
            path('agregar/', views.CargoCreateView.as_view(), name='cargo_create'),
            path('<int:pk>/actualizar/', views.CargoUpdateView.as_view(), name='cargo_update'),
            path('<int:pk>/', views.CargoDetailView.as_view(), name='cargo_detail'),
            path('<int:pk>/eliminar/', views.CargoDeleteView.as_view(), name='cargo_delete')
        ])),
        path('calificaciones/', include([
            path('', views.CalListView.as_view(), name='calificacion_list'),
            path('agregar/', views.CalCreateView.as_view(), name='calificacion_create'),
            path('<int:pk>/actualizar/', views.CalUpdateView.as_view(), name='calificacion_update'),
            path('<int:pk>/', views.CalDetailView.as_view(), name='calificacion_detail'),
            path('<int:pk>/eliminar/', views.CalDeleteView.as_view(), name='calificacion_delete')
        ])),
        path('especialidades/', include([
            path('', views.EspListView.as_view(), name='especialidad_list'),
            path('agregar/', views.EspCreateView.as_view(), name='especialidad_create'),
            path('<int:pk>/actualizar/', views.EspUpdateView.as_view(), name='especialidad_update'),
            path('<int:pk>/', views.EspDetailView.as_view(), name='especialidad_detail'),
            path('<int:pk>/eliminar/', views.EspDeleteView.as_view(), name='especialidad_delete')
        ])),
    ])),
    path('logout/', login_required(auth_views.logout), name='logout'),
    path('unidad_organizacional/', login_required(views.gestionar_unidad_org), name='gestionarUnidadOrg'),
    path('calificacion/', login_required(views.gestionar_calificacion), name='gestionarCalificacion'),
    path('departamento/', login_required(views.gestionar_departamento), name='gestionarDepartamento'),
    path('cargo/', login_required(views.gestionar_cargo), name='gestionarCargo'),
    path('especialidad/', login_required(views.gestionar_especialidad), name='gestionarEspecialidad'),
    path('seccion_sindical/', login_required(views.gestionar_seccion_sindical), name='gestionarSeccionSindical'),
    path('adicionar_unidad_organizacional/', login_required(views.adicionar_uo), name='adicionarUO'),
    path('editar_unidad_organizacional/<int:pk>/', login_required(views.editar_uo), name='editarUO'),
    path('detalle_unidad_organizacional/<int:pk>/', login_required(views.DetalleUo.as_view()), name='detalleUO'),
    path('eliminar_unidad_organizacional/<int:pk>/', login_required(views.eliminar_uo), name='eliminarUO'),
    path('adicionar_seccion_sindical/', login_required(views.adicionar_ss), name='adicionarSS'),
    path('editar_seccion_sindical/<int:pk>/', login_required(views.editar_ss), name='editarSS'),
    path('detalle_seccion_sindical/<int:pk>/', login_required(views.DetalleSs.as_view()), name='detalleSS'),
    path('eliminar_seccion_sindical/<int:pk>/', login_required(views.eliminar_ss), name='eliminarSS'),
    path('adicionar_departamento/', login_required(views.adicionar_departamento), name='adicionarDepartamento'),
    path('editar_departamento/<int:pk>/', login_required(views.editar_departamento), name='editarDepartamento'),
    path('detalle_departamento/<int:pk>/', login_required(views.DetalleDepartamento.as_view()),
         name='detalleDepartamento'),
    path('eliminar_departamento/<int:pk>/', login_required(views.eliminar_departamento), name='eliminarDepartamento'),
    path('adicionar_cargo/', login_required(views.adicionar_cargo), name='adicionarCargo'),
    path('editar_cargo/<int:pk>/', login_required(views.editar_cargo), name='editarCargo'),
    path('detalle_cargo/<int:pk>/', login_required(views.DetalleCargo.as_view()), name='detalleCargo'),
    path('eliminar_cargo/<int:pk>/', login_required(views.eliminar_cargo), name='eliminarCargo'),
    path('adicionar_calificacion/', login_required(views.adicionar_calificacion), name='adicionarCalificacion'),
    path('editar_calificacion/<int:pk>/', login_required(views.editar_calificacion), name='editarCalificacion'),
    path('detalle_calificacion/<int:pk>/', login_required(views.DetalleCalificacion.as_view()),
         name='detalleCalificacion'),
    path('eliminar_calificacion/<int:pk>/', login_required(views.eliminar_calificacion),
         name='eliminarCalificacion'),
    path('adicionar_especialidad/', login_required(views.adicionar_especialidad), name='adicionarEspecialidad'),
    path('editar_especialidad/<int:pk>/', login_required(views.editar_especialidad), name='editarEspecialidad'),
    path('detalle_especialidad/<int:pk>/', login_required(views.DetalleEspecialidad.as_view()),
         name='detalleEspecialidad'),
    path('eliminar_especialidad/<int:pk>/', login_required(views.eliminar_especialidad), name='eliminarEspecialidad'),
]

pr3/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('home_pr3/', login_required(views.home_pr3), name='home_pr3'),
    path('actualizar_coeficiente/', login_required(views.editar_coeficiente), name='actualizarCoeficiente'),
    path('datos/', login_required(views.registrar_datos), name='entradaDatos'),
    path('listar_valor_prod/', login_required(views.listar_valor_prod), name='listaValorProd'),
    path('ajustar_prod/', login_required(views.ajustar_valor_prod), name='ajustar_prod'),
    path('act_por_ot/<int:pk>/', login_required(views.act_por_ot), name='ActPorOT'),
    path('list_datos/', login_required(views.listado_datos), name='ListDatos'),
    path('vista_reporte_ot_actividades/', login_required(views.reporte_ot_actividades),
         name='visualizarReporteOTActividades'),
    path('exportar_reporte_ot_actividades/', login_required(views.exportar_ot_actividades),
         name='exportarReporteOTActividades'),
    path('vista_reporte_area_ot/', login_required(views.reporte_area_ot), name='visualizarReporteAreaOT'),
    path('exportar_reporte_area_ot/', login_required(views.exportar_area_ot), name='exportarReporteAreaOT'),
    path('vista_reporte_act_contrato/', login_required(views.reporte_actividades_contrato), name='ReporteActCont'),
    path('exportar_reporte_act_contrato/<cont>/', login_required(views.exportar_actividades_contrato),
         name='exportarReporteActCont'),
    path('vista_reporte_pr3/', login_required(views.reporte_pr3), name='visualizarReportePR3'),
    path('exportar_reporte_pr3/', login_required(views.exportar_reporte_pr3), name='exportarReportePR3'),
    path('vista_reporte_prod_dir/', login_required(views.reporte_prod_direccion), name='visualizarReporteProdDir'),
]

rechum/urls.py
from decorator_include import decorator_include
from django.contrib import admin
from django.contrib.auth.views import login
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', decorator_include(login_required, 'principal.urls')),
    path('', login, name='login_up'),
    path('rh/', include([
        path('', decorator_include(login_required, 'adm.urls')),
        path('', decorator_include(login_required, 'ges_trab.urls')),
        path('', decorator_include(login_required, 'plantilla.urls')),
        path('', decorator_include(login_required, 'capacitacion.urls')),
        path('parte-tiempo/', decorator_include(login_required, 'parte_tiempo.urls')),
        path('subsidios/', decorator_include(login_required, 'subsidio.urls')),
        path('datos-prenomina/', decorator_include(login_required, 'datos_prenom.urls')),
        path('ausentismo/', decorator_include(login_required, 'ausentismo.urls')),
        path('capacitacion/', decorator_include(login_required, 'capacitacion.urls')),
    ])),
    path('entrada-datos/', decorator_include(login_required, 'entrada_datos.urls')),
    path('facturacion/', decorator_include(login_required, 'facturacion.urls')),
    path('pr3/', decorator_include(login_required, 'pr3.urls')),
    path('pren/', decorator_include(login_required, 'prenomina15.urls')),
    re_path('^select2/', include('django_select2.urls'))
    # path('__debug__/', include(debug_toolbar.urls))
]

pr3/models.py
from django.db import models

from entrada_datos.models import OT, Actividad
from ges_trab.models import Trabajador
from rechum.models import BaseUrls


class Datos(BaseUrls, models.Model):
    orden_trab = models.ForeignKey(OT, on_delete=models.DO_NOTHING, default='', verbose_name="orden de trabajo")
    actividad = models.ForeignKey(Actividad, on_delete=models.DO_NOTHING, default='')
    trabajador = models.ForeignKey(Trabajador, on_delete=models.DO_NOTHING, default='')
    cant_horas = models.PositiveIntegerField('cantidad de horas')
    horas_ext = models.PositiveIntegerField('horas extras', default=0)
    tarifa_hor = models.DecimalField('tarifa horaria', max_digits=7, decimal_places=6, editable=False)
    prod_reportada = models.PositiveIntegerField('producción reportada', editable=False)


class DatosAnual(BaseUrls, models.Model):
    orden_trab = models.ForeignKey(OT, on_delete=models.DO_NOTHING, verbose_name="orden de trabajo")
    actividad = models.ForeignKey(Actividad, on_delete=models.DO_NOTHING)
    trabajador = models.ForeignKey(Trabajador, on_delete=models.DO_NOTHING)
    cant_horas = models.PositiveIntegerField('cantidad de horas')
    horas_ext = models.PositiveIntegerField('horas extras', default=0)
    tarifa_hor = models.DecimalField('tarifa horaria', max_digits=7, decimal_places=6, editable=False)
    prod_reportada = models.PositiveIntegerField('producción reportada', editable=False)
    fecha = models.DateField(editable=False)
    prod_tecleada = models.PositiveIntegerField('producción tecleada', default=0)


class CoeficientePromedioSalario(BaseUrls, models.Model):
    coeficiente = models.PositiveIntegerField()


class Area:
    nombre = ''
    id = ''
    ot = []
    total = 0

    def __init__(self, nombre, ot, id_a, total):
        self.nombre = nombre
        self.ot = ot
        self.id = id_a
        self.total = total


class OrdenTrabajo:
    codigo = ''
    nombre = ''
    actividades = []
    total = 0
    area = 0

    def __init__(self, codigo, nombre, actividades, total, area):
        self.codigo = codigo
        self.nombre = nombre
        self.actividades = actividades
        self.total = total
        self.area = area


class Actividades:
    orden_trab = ''
    codigo = ''
    nombre = ''
    trabajadores = []
    valor = 0
    id = ''

    def __init__(self, orden_trab, codigo, nombre, trabajadores, valor, id):
        self.orden_trab = orden_trab
        self.nombre = nombre
        self.codigo = codigo
        self.trabajadores = trabajadores
        self.valor = valor
        self.id = id


class Trabajador:
    codigo = ''
    nombre = ''
    real = 0
    extra = 0
    id = 0
    id_act =0

    def __init__(self, codigo, nombre, real, extra, id, id_act):
        self.nombre = nombre
        self.codigo = codigo
        self.real = real
        self.extra = extra
        self.id = id
        self.id_act = id_act

pr3/templates/Listado_Datos.html
{% extends "base_pr3.html" %}
{% load static %}
{% block title %}Listado de Datos{% endblock %}
{% block styles %}
    <style type="text/css">
        #tabla_list_datos_paginate a:hover {
            background-color: #007bff !important;
            color: white;
            border: solid 1px;
            border-color: #0062cc !important;
            transition: color .25s ease-in-out, background-color .25s ease-in-out, border-color .25s ease-in-out, border .25s ease-in-out;
        }

        td, th {
            padding: 2px!important;
        }
    </style>
{% endblock %}
{% block content %}
    <!-- Page Content Holder -->
    <div id="content" style="padding-top: 100px;">

        <div class=content align="center"><h5><strong>Listado de Datos</strong></h5></div>
        <div class="container" role="main" style=" margin-left: 0; font-size: smaller" >
            <div class="row">
               <div class="col-lg-12">
                    <table id="tabla_list_datos" class="display" cellspacing="0" width="100%" >
                        <thead>
                        <tr align="center">
                            <th>OT</th>
                            <th>Nombre OT</th>
                            <th style="width: 10px">Act</th>
                            <th>Nombre Act</th>
                            <th>Prod</th>
                            <th>Código</th>
                            <th>Trabajador</th>
                            <th style="width: 15px">Hrs</th>
                            <th style="width: 15px">Hrs Ext</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in list_datos %}
                            <tr>
                                <td align="center">{{ i.orden_trab.codigo_ot }}</td>
                                <td >{{ i.orden_trab.descripcion_ot }}</td>
                                <td align="center">{{ i.actividad.codigo_act }}</td>
                                <td>{{ i.actividad.descripcion_act }}</td>
                                <td align="center">{{ i.actividad.prod_tecleada }}</td>
                                <td align="center">{{ i.trabajador.codigo_interno }}</td>
                                <td>{{ i.trabajador.primer_nombre }} {{ i.trabajador.segundo_nombre }} {{ i.trabajador.apellidos }}</td>
                                <td align="center">{{ i.cant_horas }}</td>
                                <td align="center">{{ i.horas_ext }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <th style="padding: 6px 6px !important;">Código</th>
                        <th style="padding: 6px 6px !important;">Orden Trab</th>
                        <th style="padding: 6px 6px !important;">Código</th>
                        <th style="padding: 6px 6px !important;">Actividad</th>
                        <th style="padding: 6px 6px !important;">Producción</th>
                        <th style="padding: 6px 6px !important;">Código</th>
                        <th style="padding: 6px 6px !important;">Nombre y apellidos</th>
                        <th style="padding: 6px 6px !important;">Cant Horas</th>
                        <th style="padding: 6px 6px !important;">Horas Extras</th>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function () {
            // DataTable
            var table = $('#tabla_list_datos').DataTable({
                "language": {
                    processing: "Procesando...",
                    search: "Buscar:",
                    lengthMenu: "Mostrar _MENU_ registros",
                    info: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    infoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                    infoFiltered: "(filtrado de un total de _MAX_ registros)",
                    infoPostFix: "",
                    loadingRecords: "Cargando...",
                    zeroRecords: "No se encontraron resultados",
                    emptyTable: "Ningún dato disponible en esta tabla",
                    paginate: {
                        first: "Último",
                        previous: "Anterior",
                        next: "Siguiente",
                        last: "Último"
                    }
                }
            });
            // Setup - add a text input to each footer cell
            $('#tabla_list_datos').find('tfoot th').each(function () {
                var title = $(this).text();
                $(this).html('<input class="form-control" type="text" style="font-size: smaller" placeholder="Buscar ' + title + '"/>');
            });

            // Apply the search
            table.columns().every(function () {
                var that = this;

                $('input', this.footer()).on('keyup change', function () {
                    if (that.search() !== this.value) {
                        that
                            .search(this.value)
                            .draw();
                    }
                });
            });
        });
    </script>
{% endblock %}


pr3/templates/Listar_Valor_Produccion.html
{% extends "base_pr3.html" %}
{% load static %}
{% block title %}Cambio Valor Producción{% endblock %}
{% block styles %}
    <style type="text/css">
        .has-error {
            border-color: #dc3545;
            box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.25);
        }

        #tabla_act_paginate a:hover {
            background-color: #007bff !important;
            color: white;
            border: solid 1px;
            border-color: #0062cc !important;
            transition: color .25s ease-in-out, background-color .25s ease-in-out, border-color .25s ease-in-out, border .25s ease-in-out;
        }
        td, th {
            padding: 1px!important;
            class: table-succes;
        }

    </style>
{% endblock %}
{% block content %}
    <!-- Page Content Holder -->
    <div id="content" style="padding-top: 100px;">

        <div class=content align="center"><h5><strong>Listado de Valor de Producción de Actividades</strong></h5></div>
        <div class="container" role="main" style=" font-size: smaller; margin-left: 0">
            <div class="row">
                {% if errores %}
                    <div class="alert alert-dismissable alert-danger">
                        <button style="margin-left: 20px;" type="button" class="close" data-dismiss="alert"
                                aria-hidden="true"><strong> &times;</strong></button>
                        <strong>Error:</strong> {{ errores }}
                    </div>
                {% endif %}
                <br>
            <br>
                <div class="col-lg-12">
                    <table id="tabla_act" class="display table-success hover" cellspacing="0" width="100%">
                        <thead>
                        <tr align="center">
                            <th>OT</th>
                            <th>Act</th>
                            <th>Descripción</th>
                            <th>Ajuste Prod</th>
                            <th>Prod Report.</th>
                            <th>Prod Acum.</th>
                            <th>Total Venta</th>
                            <th>Venta-Prod Ac</th>
                            <th>Valor Act.</th>
                            <th>Ajuste</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in list_act %}
                            <tr>
                                <td align="center">{{ i.orden_trab.codigo_ot }}</td>
                                <td align="center">{{ i.codigo_act }}</td>
                                <td>{{ i.descripcion_act }}</td>
                                <td align="center">{{ i.prod_tecleada }}</td>
                                <td align="center">{{ i.valor_prod_act }}</td>
                                <td align="center">0</td>
                                <td align="center">{{ i.venta }}</td>
                                <td align="center">0</td>
                                <td align="center">{{ i.valor_act }}</td>
                                <td>
                                    <div class="icon-acciones" align="center">
                                        <a id="{{ i.pk }} - {{ i.prod_tecleada }}"
                                           class="badge badge-pill badge-primary ajustar">
                                            <i class="fa fa-edit" title="Ajustar Producción"
                                               style="color: white;"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <th style="padding: 6px 6px !important;">Orden de Trabajo</th>
                        <th style="padding: 6px 6px !important;">Código</th>
                        <th style="padding: 6px 6px !important;">Descripción</th>
                        <th style="padding: 6px 6px !important;">Ajuste Prod</th>
                        <th style="padding: 6px 6px !important;">Prod Reportada</th>
                        <th style="padding: 6px 6px !important;">Prod Acumulada</th>
                        <th style="padding: 6px 6px !important;">Venta</th>
                        <th style="padding: 6px 6px !important;">Valor </th>
                        <th style="padding: 6px 6px !important;">Valor Act</th>
                        <td style="padding: 6px 6px !important;"></td>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>

        <div id="popup" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm-2">
                <div class="modal-content">
                    <form id="formularioAjuste" role="form" action="{% url 'ajustar_prod' %}"
                          method="post">
                        <div class="modal-header">
                            <h5><strong>Ajustar Valor Producción</strong></h5>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            {% csrf_token %}
                            <div class="panel panel-default">
                                <div class="row" style="margin-bottom: 20px;">
                                    {% if formajuste.errors %}
                                        <div class="alert alert-danger"
                                             style="width: 100%; text-align: center; margin: 0 auto; padding: 0 10px; border-radius: 0;">
                                            <p>{{ formajuste.prod_tecleada.errors }}</p>
                                        </div>
                                    {% endif %}
                                </div>
                                <input id="codigo_act" name="codigo_act" value="" type="hidden">
                                <div class="row">
                                    <div class="col-sm-6"><strong>Ajuste Valor
                                        Producción:</strong>{{ formajuste.prod_tecleada }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="col-lg-12 text-right">
                                <input id="enviar" type="submit" class="btn btn-primary" name="submit" value="Guardar">
                                <button type="button" class="btn btn-danger" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    <script type="text/javascript">

        $('.badge.badge-pill.badge-primary.ajustar').click(function () {
            var nombre = this.id.split('-');
            $('#popup input#codigo_act').prop('value', nombre[0]);
            $('#popup').modal('show');
        });

        function validarFormulario() {
            if (AjusteProd()) {
                $('#enviar').removeAttr('disabled');
            } else {
                $('#enviar').attr('disabled', '');
            }
        }

        $(document).ready(function () {
            validarFormulario();
        });

        {% if formajuste.errors %}
            $('#popup').modal('show');
        {% endif %}

    </script>
    <script type="text/javascript">
        exp_monto = "^([0-9]{1,5}){1}(([,]{1})([0-9]{0,2}))?";
        $('#id_prod_tecleada').prop("title", 'Ajuste Producción').attr("oninvalid", 'setCustomValidity("Campo obligatorio, numérico hasta 99999")').on('change', function () {
            validarFormulario();
        });

        {% if form.errors %}
            $('#popup').modal('show');
        {% endif %}

        function AjusteProd() {
            var cadena = $('#id_prod_tecleada')[0].value;
            if (!(cadena.match(exp_monto))) {
                $('#id_prod_tecleada').addClass('has-error');
                return false;
            } else {
                $('#id_prod_tecleada').removeClass('has-error');
                return true;
            }
        }

        $("#formularioAjuste").on('keyup', function () {
            validarFormulario();
        });

        $(document).ready(function () {
            // DataTable
            var table = $('#tabla_act').DataTable({
                "language": {
                    processing: "Procesando...",
                    search: "Buscar:",
                    lengthMenu: "Mostrar _MENU_ registros",
                    info: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    infoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                    infoFiltered: "(filtrado de un total de _MAX_ registros)",
                    infoPostFix: "",
                    loadingRecords: "Cargando...",
                    zeroRecords: "No se encontraron resultados",
                    emptyTable: "Ningún dato disponible en esta tabla",
                    paginate: {
                        first: "Último",
                        previous: "Anterior",
                        next: "Siguiente",
                        last: "Último"
                    }
                }
            });
            // Setup - add a text input to each footer cell
            $('#tabla_act').find('tfoot th').each(function () {
                var title = $(this).text();
                $(this).html('<input class="form-control" type="text" style="font-size: smaller" placeholder="Buscar ' + title + '"/>');
            });

            // Apply the search
            table.columns().every(function () {
                var that = this;

                $('input', this.footer()).on('keyup change', function () {
                    if (that.search() !== this.value) {
                        that
                            .search(this.value)
                            .draw();
                    }
                });
            });
        });
    </script>
{% endblock %}


pr3/templates/home_pr3.html
{% extends "base_pr3.html" %}
{% block content %}
    <!-- Page Content Holder -->
    <div id="content" style="padding-top: 100px;">
        <div align="center" style="padding-top: 50px"><h1>Sub-Sistema PR3</h1></div>

    </div>


{% endblock %}
{% block javascript %}

{% endblock %}